<?php echo '<?xml version="1.0" encoding="UTF-8" ?>'.PHP_EOL;?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

	<!-- generator="WordPress/6.2.2" created="2023-08-04 00:55" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
		<title>{{ $blog->getBlogTitle() }}</title>
		<link>{{ $blog->getDomain() }}</link>
		<description>{{ $blog->getDescription() }}</description>
		<pubDate>{{ $blog->getPubDate() }}</pubDate>
		<language>{{ $blog->getLanguage() }}</language>
		<wp:wxr_version>{{ $blog->getWxrVersion() }}</wp:wxr_version>
		<wp:base_site_url>{{ $blog->getBaseSiteUrl() }}</wp:base_site_url>
		<wp:base_blog_url>{{ $blog->getBaseBlogUrl() }}</wp:base_blog_url>
		
	<generator>https://wordpress.org/?v=6.2.2</generator>

    @foreach($blog->getPosts() as $post)
    <item>
        <title><![CDATA[{{ $post->getTitle() }}]]></title>
        <link></link>
        <pubDate></pubDate>
        <dc:creator><![CDATA[]]></dc:creator>
        <guid isPermaLink="false"></guid>
        <description>{{ $post->getDescription() }}</description>
        <content:encoded><![CDATA[{!! $post->getContent() !!}]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id></wp:post_id>
        <wp:post_date><![CDATA[{{ $post->getPostDate() }}]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[]]></wp:post_date_gmt>
        <wp:post_modified><![CDATA[{{ $post->getPostDate() }}]]></wp:post_modified>
        <wp:post_modified_gmt><![CDATA[]]></wp:post_modified_gmt>
        <wp:comment_status><![CDATA[close]]></wp:comment_status>
        <wp:ping_status><![CDATA[open]]></wp:ping_status>
        <wp:post_name><![CDATA[]]></wp:post_name>
        <wp:status><![CDATA[draft]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[post]]></wp:post_type>
        <wp:post_password><![CDATA[]]></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
        <category domain="category" nicename="{{ $post->getCategoryEn() }}"><![CDATA[{{ $post->getCategoryJa() }}]]></category>
        <wp:postmeta>
		<wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
		<wp:meta_value><![CDATA[{{ $post->getThumbnailId() }}]]></wp:meta_value>
		</wp:postmeta>
    </item>
    @endforeach

	</channel>
</rss>